### ISSUE TITLE
check token validation

### ISSUE THREAD

**Issue by geraxe** [kaltura/nginx-akamai-token-validate-module#11]
nginx-secure-token-module 1.3 not work with nginx-akamai-token-validate-module 1.1
stable 403 invalid token for different query variable names ("__hdnea__" and i try other names)
after downgrading nginx-akamai-token-validate-module to 1.0.1 all worked fine 

please check

**Comment by erankor** [comment]
Please share your configuration and the URL that fails

**Comment by DBezemer** [comment]
@erankor same issue for me, can share the used config privately with you

**Comment by erankor** [comment]
Added a sample configuration to the readme, closing this issue
