### ISSUE TITLE
How to create an akamai token dynamically?

### ISSUE THREAD

**Issue by qhchen2** [kaltura/nginx-akamai-token-validate-module#16]
I wasnt exactly sure where to post this because Im trying to use so many modules and a random token generator but this seemed the appropriate location

Im using nginx-vod-module, nginx-secure-token-module and nginx-akamai-token-validate-module in conjunction, as Im trying to execute the approach that erankor outlined in https://github.com/kaltura/nginx-secure-token-module/issues/20
So far Ive only integrated the vod and the akamai token validate module in the following conf

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {
	# gzip manifests
	gzip on;
	gzip_types application/vnd.apple.mpegurl;


		#vod configuration
	server {
        listen 8081;
		
		# vod settings
		vod_mode mapped;
		
		# vod caches
		#vod_metadata_cache metadata_cache 512m; 
		#vod_response_cache response_cache 128m;
		#vod_mapping_cache mapping_cache 5m;
		
		
		# file handle caching
		open_file_cache          max=1000 inactive=5m;
		open_file_cache_valid    2m;
		open_file_cache_min_uses 1;
		open_file_cache_errors   on;
		
		if ($arg_token) {
			set $test_token $arg_token;
		}

		if ($cookie_token) {
			set $test_token $cookie_token;
		}
		
		location /hls/ {
			akamai_token_validate $test_token;
			akamai_token_validate_key 1234;
			
			vod hls;
			alias /mp4/;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```

I have confirmed that before inserting the directives by akamai-token-validate-module the following URL was playable `http://myIP:8081/hls/static.json/master.m3u8` and that after it gave
`Server returned 403 Forbidden (access denied)`

Now I wanted to test if adding an akamai token gave access to the m3u8. I  generated a token via [akamai token generator](https://github.com/anilGupta/akamai-token-generator)

However Im getting access denied on that URL
`http://myIP:8081/hls/static.json/master.m3u8?token=st=1527874650~exp=1527934650~acl=/hls/*~hmac=6e81f1a843661ee631a4b62f631f2f6a36b: Server returned 403 Forbidden (access denied)`

the node module generated everything after the question mark, I added the question mark because I wasnt sure what an Akamai tokenized URL looks like

Does anybody have a clue what went wrong? Is my token incorrect?  Is my conf wrong?  Or something else? Should I use a different way of creating the token? I want to test if I can play a tokenized URL but its not giving access so I dont know whats the problem. Im not sure if its the module or the way Im generating the token.

My goal is a simple authenticated m3u8 playable URL, but I read that the secure token module doesnt work with simple self created tokens that only needs to change infrequently to be used in a simple html. So I chose to implement akamai token because of the existence of akamai-token-validate-module even though an akamai token seems to be too complicated for my use case, since its  appears to even be IP-based (not sure). and because of that its probably best to generate it on the fly via my html so that everyclient has a different token?
In that case am I going about it the wrong way by manually creating and testing the token?

I used the following settings for the token generator module and ran via node

```
var Akamai = require('akamai-auth-token');
var config = {
         algorithm : 'SHA256',
         acl : '/hls/*',
         window : 60000,
         key : "1234",
         encoding: false
    };
 
 
 var akamai = new Akamai.default(config),
     token = akamai.generateToken();
	 console.log(token);
```

EDIT: I just saw that I didnt copy the akamai token string properly. the hmac was `6e81f1a843661ee631a4b62f631f2f6a36b5be9efbb2cbd02743f5687ca03e2c` and I was able to download the m3u8 that way. So Ive confirmed that the basic functionality of this module works. I still dont have access to the ts segments so Im guessing that I need the secure-token-module for that

However Im still looking for the answer if its possible to somehow generate this token dynamically. in a html? Maybe through a JS? So that this html will always have access to the m3u8, but not sombody else who has just the m3u8 link?

Changed title from `How can I test this modules functionality?` to `How to create an akamai token dynamically?`

**Comment by erankor** [comment]
1. Yes, in order to add tokens to the segment URLs you can use nginx-secure-token-module
2. It's problematic to generate tokens in html/JS, since it means the secret will be exposed to the client. The tokens should be generated by some server side code. A possible flow is for example - 
  a. The users log in to the app, and the server returns some session cookie
  b. When a user wants to play a video, the player performs some call to the server in order to get the URL
  c. The server validates the session cookie, and if found valid, returns a tokenized URL

**Comment by qhchen2** [comment]
Hi erankor, thanks for the advice. Now Im getting some strange behavior with the nodejs module. I made a second token and for some reason this was rejected, so now Im wondering if the nodejs module creates an akamai token that is exactly the right format. Do you by any chance have a tested to work example script for the server side that returns a tokenized URL that is exactly the right format?

The following token didnt work, From your experience, do you see something wrong with it? Im not actually sure what `st` and `hmc` exactly are, do you know? `exp` should be the expiration and `acl` the access control location, I think.
`http://myIP:8081/hls/static.json/master.m3u8?token=st=1527887497~exp=6e+39~acl=/hls/*~hmac=1d8ef6de67ab45a5cac05d36bf8016b7b2770e40ec0294bff8b65a52cdfbe376`

Also to pass tokens to segment URLs Is adding the following lines enough? I took these from the documentation examples
```
http{
	secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}
server{
location{
			secure_token $token;
			secure_token_types text/xml application/vnd.apple.mpegurl;
             }
}
}
```
But I thought `text/xml` should be something else, the segment MIME.type? I dont know what `text/xml` is for. Because these lines didnt work for me (for the first token that did work). I wasnt able to play the stream.

**Comment by erankor** [comment]
The exp param looks wrong, it uses exponential notation, and it's way too large. 
The mime types that are passed to `secure_token_types` should be the mime types of manifests, not the mime types of segments, text/xml is what this module returns for MSS.

**Comment by qhchen2** [comment]
Hi erankor, Thanks for the reply, looks like youre right, when I set the window to something small like one hour or 1 day the token is always accepted.

I also saw that you answered my other question already in https://github.com/kaltura/nginx-secure-token-module/issues/48

Now the only thing I cannot figure out is how to pass the token from the m3u8 to the segments automatically, which you said could be done with nginx-secure-token-module.

I tried out the examples `HLS packaging with Akamai tokens `and
`Adding token security on top of an existing HDS/HLS live stream`
adding to the conf the following

```
secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}
	server {
		location /hls/ {
			secure_token $token;
			secure_token_types application/vnd.apple.mpegurl;
			secure_token_expires_time 100d;
			secure_token_query_token_expires_time 1h;
		}
	}
```
or
```
secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}
	server {
		location /hls/ {
			secure_token $token;
			secure_token_types text/xml application/vnd.apple.mpegurl;		
			secure_token_content_type_f4m text/xml;			
			secure_token_expires_time 100d;
			secure_token_query_token_expires_time 1h;
		}
	}
```

but I just cannot get the tokenized URL to play properly in players like vlc or ffplay, even though I can download the tokenized m3u8 in a browser.

Do you know what Im missing here? Which are the key directives to pass the token to the segments? I looked through the documention but didnt spot anything that could be what you were alluding to. I saw in a different example the directive `secure_token_tokenize_segments off;`, however this is the only reference to this directive on that entire page, and adding secure_token_tokenize_segments on; does not work for me.

Maybe it has something to do with
```
secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}
```
and I should change these parameters? Do you know?

**Comment by erankor** [comment]
Do you see tokens in the m3u8? can you paste the m3u8 here?

**Comment by qhchen2** [comment]
when I add the lines from secure-token-module to get the conf

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {
	# gzip manifests
	gzip on;
	gzip_types application/vnd.apple.mpegurl;

	secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}

	#vod configuration
	server {
        listen 8081;
		
		# vod settings
		vod_mode mapped;
		
		if ($arg_token) {
			set $test_token $arg_token;
		}

		if ($cookie_token) {
			set $test_token $cookie_token;
		}

		location /hls/ {
			akamai_token_validate $test_token;
			akamai_token_validate_key 1234;

			secure_token $token;
			secure_token_types text/xml application/vnd.apple.mpegurl;		
			secure_token_content_type_f4m text/xml;
			secure_token_expires_time 100d;
			secure_token_query_token_expires_time 1h;
			secure_token_tokenize_segments on;
			
			vod hls;
			alias /mp4/;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
with the tokenized URL
`http://myIP:8081/hls/static12.json/master.m3u8?token=st=1528033089~exp=1528036689~acl=/hls/*~hmac=75aa31dd3ddb3a5c64baf27879818f8b5d8223331fe6fe246df21ebf79a0b94c`
The contents of the M3U8 are
```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=272386,RESOLUTION=640x480,FRAME-RATE=15.151,CODECS="avc1.640016,mp4a.40.2"
http://myIP:8081/hls/static12.json/index-v1-a1.m3u8?__hdnea__=st=1528033798~exp=1528120198~acl=/hls/static12.json/*~hmac=f6fab508d559770cb6edb06ba56067f21efa0b6d1a4f7b95a621e273c7b38fea
```
shouldnt it be `?token=` instead of `?__hdnea__=`?
and shouldnt `acl=/hls/static12.json/*` be `acl=/hls/*`?

EDIT: I just checked my vlc.log and it said

`adaptive error: Failed reading http://myIP:8081/hls/static12.json/index-v1-a1.m3u8?__hdnea__=st=1528035834~exp=1528122234~acl=/hls/static12.json/*~hmac=e13f7ef9a49a631e0328e072c22fc2ccd20390613d252856033903286706f93b: HTTP/1.1 403 Forbidden`

for some reason hdnea is inserted instead of token? but nowhere in my directives am I inserting hdnea?

**Comment by erankor** [comment]
1. Yes, you need to add `param_name token` under the secure_token_akamai block
2. The ACL is fine, it is more specific than `/hls/*` which is good

**Comment by qhchen2** [comment]
Hi erankor, thanks for those tips! Indeed, adding param_name did the trick, youre amazing!

Now Im just wondering if this configuration can be generalized to a different server that also serves a HLS stream, but live, instead of vod. I saw in the documentation that all 8 secure_token directives can be placed in the http context instead of a location of a single server. I just did that but got

```
curl http://myIP:8081/hls/static12.json/master.m3u8?token=st=1528036952~exp=1528040552~acl=/hls/*~hmac=abe682dc7959d1e89bb159ef117a7167b0af5c46ef0b3136722c23e95363b6a8
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=272386,RESOLUTION=640x480,FRAME-RATE=15.151,CODECS="avc1.640016,mp4a.40.2"
http://myIP:8081/hls/static12.json/index-v1-a1.m3u8?token=st=1528039298~exp=1528125698~acl=/hls/static12.json/*~hmac=40332cc7b0cb7bc1f375203baf0a88bc63a7cc1ecfcbae43444001c6aec8daa7
```
and

```
curl http://myIP:8080/hls/test.m3u8?token=st=1528036952~exp=1528040552~acl=/hls/*~hmac=abe682dc7959d1e89bb159ef117a7167b0af5c46ef0b3136722c23e95363b6a8
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>
```

with a conf like this

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {

	akamai_token_validate $test_token;
	akamai_token_validate_key 1234;

	secure_token $token;
	secure_token_types text/xml application/vnd.apple.mpegurl;		
	secure_token_content_type_f4m text/xml;
	secure_token_expires_time 100d;
	secure_token_query_token_expires_time 1h;
	secure_token_tokenize_segments on;
	# gzip manifests
	gzip on;
	gzip_types application/vnd.apple.mpegurl;

	secure_token_akamai $token {
		key 1234;
		acl "$secure_token_baseuri_comma*";
	}
#other hls stream
server {
        listen 8080;

		if ($arg_token) {
			set $test_token $arg_token;
		}

		if ($cookie_token) {
			set $test_token $cookie_token;
		}

    location /{
    }
}

	#vod configuration
	server {
        listen 8081;
		
		# vod settings
		vod_mode mapped;
		
		if ($arg_token) {
			set $test_token $arg_token;
		}

		if ($cookie_token) {
			set $test_token $cookie_token;
		}

		location /hls/ {
			
			vod hls;
			alias /mp4/;
			
			add_header Access-Control-Allow-Headers '*';
			add_header Access-Control-Expose-Headers 'Server,range,Content-Length,Content-Range';
			add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS';
			add_header Access-Control-Allow-Origin '*';
			expires 100d;
		}
	}
}
```
So Im wondering does the authentication of secure-token-module with akamai-token-validate-module only work properly with the vod module, or is it multipurpose for as many servers as you have? 

If it is multipurpose, what is the best way to duplicate the behavior that worked for the vod mapped server to a different one? Because putting it all in http doesnt seem to work for the other server, it still works for the vod server though.

Sorry for all the extra questions, I just need to make sure its possible, then I can try out different configurations by myself.

EDIT: nvm, it works. The solution was simple copy pasting. Thanks for the help erankor!
