### ISSUE TITLE
additional null character getting passed after using akamai_token_validate_strip_token, proxypass, and rewriting while passing additional parameter

### ISSUE THREAD

**Issue by RamirezTuco** [kaltura/nginx-akamai-token-validate-module#18]
Hi, 
I am trying to use the nginx-akamai-token-validate-module, and doing a rewrite, akamai_token_validate_strip_token, and passing it to a proxy.

akamai_token_validate_strip_token works in the above use case when only the __hdnea__ param is provided, but when any other param is provided like uuid below, an url which is passed to the upstream proxy has additional "\x00" appended to the end, and nginx gives a 400 error.

Below is the nginx conf.

`
secure_token_akamai $token {
      key "1234";
      acl "/*";
}

server {
        listen 81 default_server;
        root /var/www/html;
	underscores_in_headers on;
        index index.html index.htm index.nginx-debian.html index.php;

        location / {
                try_files $uri $uri/ =404;
        }
	location ~* ^/(demo.test.com)/.*.(m3u8|mpd)$ {
		if ($arg___hdnea__) {
        	set $test_token $arg___hdnea__;
		}

		if ($cookie___hdnea__) {
        	set $test_token $cookie___hdnea__;
		}

		akamai_token_validate $test_token;
		akamai_token_validate_key 1234;
		akamai_token_validate_strip_token __hdnea__;
		
		rewrite  ^/demo.test.com/(.*)$ /$1 break;	
		
		proxy_set_header Host $http_host;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_cache off;
		proxy_pass http://127.0.0.1:82;

		secure_token $token;
		secure_token_avoid_cookies on;
		secure_token_types text/xml application/vnd.apple.mpegurl;
		secure_token_content_type_f4m text/xml;
		secure_token_expires_time 100d;
		secure_token_query_token_expires_time 4s;
}
}
`

For Upstream server it is
`
server {
        listen 82 default_server;
        root /var/www/html;
	underscores_in_headers on;
        index index.html index.htm index.nginx-debian.html index.php;

        location / {
                try_files $uri $uri/ =404;
        }

	location /video/ {
        }
}
`

The URL
http://localhost:81//demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838

works well, but if we add some additional param like

http://localhost:81//demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838&uuid=testuuid

The above gives an error.

Below are the logs.
on nginx on 81.
AccessLogs

 127.0.0.1 | - | localhost | [26/Jun/2020:12:42:07 +0530] | - | "GET //demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838 HTTP/1.1" | 200 | 590 | "-" | "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" | 0.001 | 0.000 | 127.0.0.1:82 | - | "- - - -" | http
 127.0.0.1 | - | localhost | [26/Jun/2020:12:42:43 +0530] | - | "GET //demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838&uuid=testuuid HTTP/1.1" | 400 | 157 | "-" | "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" | 0.001 | 0.000 | 127.0.0.1:82 | - | "- - - -" | http

Error logs on 81.
2020/06/26 12:42:43 [notice] 12032#0: *19 "^/demo.test.com/(.*)$" matches "/demo.test.com/video/playlist1.m3u8", client: 127.0.0.1, server: , request: "GET //demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838&uuid=testuuid HTTP/1.1", host: "localhost:81"
2020/06/26 12:42:43 [notice] 12032#0: *19 rewritten data: "/video/playlist1.m3u8", args: "__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838&uuid=testuuid", client: 127.0.0.1, server: , request: "GET //demo.test.com/video/playlist1.m3u8?__hdnea__=st=1593155393~exp=1593215393~acl=/*~hmac=f14b0be8ea886ab15210c51bd0b4a318ea60bee7682f988bf0428c5d97e7c838&uuid=testuuid HTTP/1.1", host: "localhost:81"

on upstream nginx on 82.
AccessLogs
 127.0.0.1 | 127.0.0.1 | localhost | [26/Jun/2020:12:42:07 +0530] | - | "GET /video/playlist1.m3u8 HTTP/1.0" | 200 | 230 | "-" | "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" | 0.000 | - | - | - | "- - - -" | http
 127.0.0.1 | - |  | [26/Jun/2020:12:42:43 +0530] | - | "GET /video/playlist1.m3u8?uuid=testuuid\x00 HTTP/1.0" | 400 | 157 | "-" | "-" | 0.000 | - | - | - | "- - - -" | http

Note the additional '\x00' above.

Error Log on 82.
2020/06/26 12:40:01 [info] 12178#0: *9 client sent invalid request while reading client request line, client: 127.0.0.1, server: , request: "GET /video/playlist1.m3u8?uuid HTTP/1.0"
2020/06/26 12:42:43 [info] 12178#0: *13 client sent invalid request while reading client request line, client: 127.0.0.1, server: , request: "GET /video/playlist1.m3u8?uuid=testuuid HTTP/1.0"

**Comment by erankor** [comment]
@RamirezTuco, thanks for reporting this issue!
Please try this pull #19

**Comment by RamirezTuco** [comment]
@erankor it is working as expected. Thanks.

**Comment by erankor** [comment]
Thanks, merged
