### ISSUE TITLE
Fails after "use nginx variables to define the token" changes

### ISSUE THREAD

**Issue by phillipseamore** [kaltura/nginx-akamai-token-validate-module#9]
Hi,

Updated to latest commit and simply changed my config by removing "akamai_token_validate_param_name token" and changing "akamai_token_validate on" to "akamai_token_validate $arg_token".

Now I get a 500 error on all requests.

Since NGX_HTTP_INTERNAL_SERVER_ERROR is used in 3 places I changed them to other error codes.  It looks like the error is coming from:
`if (ngx_http_arg(r, conf->strip_token.data, conf->strip_token.len, &token) != NGX_OK)`

My requests look like this:
`GET /content/file.mp4/master.m3u8?token=ip=192.168.10.245/32~st=1493297578~exp=1493308378~acl=/content/file.mp4/*~id=sessionid~hmac=b7b7bf06611aac552f7fa241f506d2c52dc415ff2b2b5a6de46b3d60684a46fd`

**Comment by erankor** [comment]
What did you set `strip_token` to? it should be set to the string `token` for this URL

**Comment by phillipseamore** [comment]
It was set to "none" - changing it to "token" fixes everything.

The readme doesn't say anything about this being needed now so would suggest updating:

> When enabled, the token is stripped off the request URI. This setting is useful when the validated requests are proxied to some upstream server (using proxy_pass), it hides the token from the upstream server

**Comment by erankor** [comment]
Updated the readme to clarify the purpose of this parameter - https://github.com/kaltura/nginx-akamai-token-validate-module/pull/10
